models:
  gemma4-26b-reasoning:
    cmd: llama-server --port ${PORT} -hf ggml-org/gemma-4-26B-A4B-it-GGUF --no-mmap --fit on -c 128000 --reasoning on
  
  gemma4-26b-no-reasoning:
    cmd: llama-server --port ${PORT} -hf ggml-org/gemma-4-26B-A4B-it-GGUF --no-mmap --fit on -c 128000 --reasoning off

  qwen3.6-27b-reasoning:
    cmd: llama-server --port ${PORT} -hf unsloth/Qwen3.6-27B-GGUF --no-mmap --fit on -c 128000 --reasoning on
  
  qwen3.6-27b-no-reasoning:
    cmd: llama-server --port ${PORT} -hf unsloth/Qwen3.6-27B-GGUF --no-mmap --fit on -c 128000 --reasoning off

  
